
 
os: Visual Studio 2019
platform: x64

for:

#
# Visual Studio (Native)
#
-
  matrix:
    only:
      - type: native

  environment:
    PATH: '%PATH%;C:\Program Files\NASM'

  install:
    - ps: Start-FileDownload "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe" -FileName "nasm-installer-x64.exe"
    - nasm-installer-x64.exe /S

  build_script:
    - mkdir build_msbuild
    - cd build_msbuild
    - cmake -G "Visual Studio 16 2019" -DENABLE_BUILD_VMM=NO -DENABLE_BUILD_TEST=OFF ..
    - msbuild /m:3 hypervisor.sln



   
    
