
#
# Setup
#
os: Visual Studio 2019
platform: x64

environment:
  matrix:
    - type: native
    - type: cygwin
    
install:
  - git submodule update --init --recursive
  
artifacts:
    - path: public


for:

#
# Visual Studio (Native)
#
-
  matrix:
    only:
      - type: native

  environment:
    PATH: '%PATH%;C:\Program Files\NASM'

  install:
    - ps: Start-FileDownload "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe" -FileName "nasm-installer-x64.exe"
    - nasm-installer-x64.exe /S

  build_script:
    - mkdir build_msbuild
    - cd build_msbuild
    - cmake -G "Visual Studio 16 2019" -DENABLE_BUILD_VMM=NO -DENABLE_BUILD_TEST=OFF ..
    - msbuild /m:3 hypervisor.sln
  #  - cmake --build . --target unittest

on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "%GIT_USER_EMAIL%"
    - git config --global user.name "%GIT_USER_NAME%"
    - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
    - cd %TEMP%\static-site
    - del * /f /q
    - for /d %%p IN (*) do rmdir "%%p" /s /q
    - SETLOCAL EnableDelayedExpansion & robocopy "%APPVEYOR_BUILD_FOLDER%\public" "%TEMP%\static-site" /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (IF !ERRORLEVEL! EQU 3 (exit 0) ELSE (exit 1))
    - git add -A
    - git commit -m "Update Static Site"
    - git push origin %TARGET_BRANCH%


  test: off

#
# Cygwin
#
-
  matrix:
    only:
      - type: cygwin

  environment:
    CYG_ROOT: C:\cygwin_bareflank
    CYG_BASH: C:\cygwin_bareflank\bin\bash
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_PACKAGES: make,gcc-core,gcc-g++,nasm,clang,clang++,cmake,python,gettext,wget,unzip
    CMAKE_URL: https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-win64-x64.zip

  install:
    - ps: Start-FileDownload "https://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"
    - setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_ROOT%\var\cache\setup" --packages "%CYG_PACKAGES%"

  build_script:
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; wget %CMAKE_URL%"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; unzip cmake-3.13.4-win64-x64.zip"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; mkdir build_cygwin"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; ../cmake-3.13.4-win64-x64/bin/cmake .. -G \"Unix Makefiles\" -DENABLE_BUILD_VMM=OFF -DENABLE_BUILD_TEST=ON -DCMAKE_C_COMPILER_WORKS=ON'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; make -j3"'

  test: off
